/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 Shubham Gupta <shubhamg13.work@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Auto-generated Rust FFI bindings for the CANN C++ adapter's public C API.
//!
//! Generated by `bindgen` in `build.rs` (`build_cann_bindings`) from the
//! adapter's self-contained public C headers (`src/executors/cann_shim/*.h`).
//! Only available with the `cann-runtime` feature, which also compiles and
//! links the adapter itself.

pub(crate) mod sys {
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(non_upper_case_globals)]
    #![allow(dead_code)]
    #![allow(clippy::missing_safety_doc)]
    include!(concat!(env!("OUT_DIR"), "/cann_bindings.rs"));
}

pub(crate) use sys::*;
